/* COZY HOME main.js - Product renderer and WhatsApp integration */
const STORE = {name: 'Cozy Home', wa: '+21600000000', domain: 'cozy-home.tn', currency: 'TND'};
function buildWaLink(product, customMsg) {const msg = customMsg || product.whatsapp_msg || 'Hello! I want to order: *' + product.name + '* - ' + product.price + ' ' + STORE.currency;return 'https://wa.me/' + STORE.wa.replace(/\D/g,'') + '?text=' + encodeURIComponent(msg);}
function fmtPrice(n) {return n.toFixed(3).replace('.', ',') + ' TND';}
function discountPct(price, compare) {if (!compare || compare <= price) return 0;return Math.round((1 - price / compare) * 100);}
async function loadProducts() {try {const res = await fetch('/products.json');const data = await res.json();return Array.isArray(data) ? data : (data.products || []);} catch {return [];}}
function productCardHTML(p) {const disc = discountPct(p.price, p.compare_price);const imgSrc = p.images && p.images[0] ? p.images[0] : null;const img = imgSrc ? '<img src="' + imgSrc + '" alt="' + p.name + '" loading="lazy" onload="this.style.animation=\'imgFadeIn 0.6s ease-in-out\'"/>' : '<div class="product-card__img-placeholder">X</div>';const badge = disc > 0 ? '<span class="product-card__badge">-' + disc + '%</span>' : (p.featured ? '<span class="product-card__badge product-card__badge--new">NEW</span>' : '');const chips = (p.highlights || []).slice(0,3).map(h => '<span class="highlight-chip">' + h + '</span>').join('');const waLink = buildWaLink(p);return '<article class="product-card" data-id="' + p.id + '"><a href="/product.html?id=' + p.id + '" class="product-card__img">' + img + badge + '</a><div class="product-card__body"><a href="/product.html?id=' + p.id + '"><div class="product-card__name">' + p.name + '</div></a>' + (chips ? '<div class="product-card__highlights">' + chips + '</div>' : '') + '<div class="product-card__prices"><span class="price-current">' + fmtPrice(p.price) + '</span>' + (p.compare_price ? '<span class="price-compare">' + fmtPrice(p.compare_price) + '</span>' : '') + (disc > 0 ? '<span class="price-save">-' + disc + '%</span>' : '') + '</div></div><div class="product-card__footer"><a href="' + waLink + '" target="_blank" class="btn-wa">Order via WhatsApp</a></div></article>';}
async function renderProductGrid(containerId, opts = {}) {const container = document.getElementById(containerId);if (!container) return;const all = await loadProducts();let products = all.filter(p => p.active !== false);if (opts.featured) products = products.filter(p => p.featured);if (opts.limit) products = products.slice(0, opts.limit);if (opts.category) products = products.filter(p => p.category === opts.category);if (products.length === 0) {container.innerHTML = '<div class="empty-state"><h3>No products available</h3></div>';return;}container.innerHTML = products.map(productCardHTML).join('');}
function initFilters(gridId) {document.querySelectorAll('.filter-btn').forEach(btn => {btn.addEventListener('click', async () => {document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));btn.classList.add('active');const all = await loadProducts();const container = document.getElementById(gridId);let products = all.filter(p => p.active !== false);container.innerHTML = products.map(productCardHTML).join('');});});}
function initSearch(inputId, gridId) {const input = document.getElementById(inputId);if (!input) return;let all = [];loadProducts().then(p => { all = p.filter(x => x.active !== false); });input.addEventListener('input', () => {const q = input.value.toLowerCase();const filtered = q ? all.filter(p => p.name.toLowerCase().includes(q) || (p.description || '').toLowerCase().includes(q)) : all;document.getElementById(gridId).innerHTML = filtered.map(productCardHTML).join('');});}
window.STORE = STORE; window.buildWaLink = buildWaLink; window.fmtPrice = fmtPrice; window.loadProducts = loadProducts; window.renderProductGrid = renderProductGrid; window.initFilters = initFilters; window.initSearch = initSearch;